# Generated by Django 3.2 on 2022-05-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fsc_products', '0007_alter_product_image'),
        ('fsc_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_desc', models.TextField(max_length=450)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsc_products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsc_users.userprofile')),
            ],
        ),
    ]
