# Generated by Django 3.2 on 2022-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsc_reviews', '0002_rename_prod_desc_review_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(null=True),
        ),
    ]
