# Generated by Django 3.2 on 2022-05-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsc_reviews', '0003_review_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(default=2),
        ),
    ]
