# Generated by Django 3.2 on 2022-05-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsc_users', '0001_initial'),
        ('fsc_products', '0009_auto_20220522_0936'),
        ('fsc_reviews', '0004_alter_review_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fsc_products.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fsc_users.userprofile'),
        ),
    ]
