# Generated by Django 3.2 on 2022-05-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsc_reviews', '0005_auto_20220522_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
