# Generated by Django 3.2 on 2022-05-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsc_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='name',
        ),
    ]
