# Generated by Django 3.2 on 2022-05-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsc_users', '0002_favouriteslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouritesList',
        ),
    ]
